### PR TITLE
workflows/sync-triage-config: sign commits

### PR DESCRIPTION
**Pull request by Rylan12**
Sign the synchronization commits in PRs opened by the `sync-triage-config` workflow.

The `BREWTESTBOT_GPG_SIGNING_SUBKEY` and `BREWTESTBOT_GPG_SIGNING_SUBKEY_PASSPHRASE` secrets will need to be added to this repo if they're not already accessible.

CC: @MikeMcQuaid and @Bo98

### CODE REVIEW

**Review by Bo98 — APPROVED** [review]

**Comment by Bo98** [comment]
> The `BREWTESTBOT_GPG_SIGNING_SUBKEY` and `BREWTESTBOT_GPG_SIGNING_SUBKEY_PASSPHRASE` secrets will need to be added to this repo if they're not already accessible.

Done now.

**Review by MikeMcQuaid — APPROVED** [review]
👏🏻 great work.

**Comment by Rylan12** [comment]
Think we should test this or just wait for the next configuration change (which will likely be a dependabot update for one of the actions in the `triage-issues` workflow)?

Either way: I don't have write access here so I'll need one of you to merge.

**Comment by Bo98** [comment]
Does it update open PRs? The Homebrew/cask PR is still open.

**Comment by Rylan12** [comment]
I think so... I guess let's check and see.

If not, we can close that PR and rerun the workflow to reopen it from scratch to test

**Comment by Rylan12** [comment]
So, it looks like it did [detect that a PR was already open](https://github.com/Homebrew/.github/runs/2278745723?check_suite_focus=true#step:7:545) and [claims to have updated it](https://github.com/Homebrew/.github/runs/2278745723?check_suite_focus=true#step:7:546), but it didn't seem to actually work. Not sure where the issue is. For now, it might be easier to just close that PR and rerun the workflow.

**Comment by Bo98** [comment]
Yeah it didn't push anything since `git diff` detected the branches as even. I've closed the PR and started a re-run.

**Comment by Rylan12** [comment]
I thought it checked the diff between the branch and `master` but I guess not.

**Comment by Bo98** [comment]
The sign was:

> Branch 'sync-triage-config' is even with its remote and will not be updated

**Comment by Bo98** [comment]
Seems to work: https://github.com/Homebrew/homebrew-cask/pull/103221

**Pull request merged**
