### PR TITLE
workflows/sync-triage-config: sync more repos

### PR DESCRIPTION
**Pull request by Rylan12**
Add `Homebrew/homebrew-formula-analytics` and `Homebrew/rubydoc.brew.sh` to the list of repos to sync.

CC: @MikeMcQuaid

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by Rylan12** [comment]
I don't have write permission here so if this is good you'll need to merge it

**Comment by Rylan12** [comment]
A few of the new jobs are failing with the following message:

```
  /usr/bin/git push --force-with-lease origin HEAD:refs/heads/sync-triage-config
  remote: Permission to Homebrew/actions.git denied to BrewTestBot.
  fatal: unable to access 'https://github.com/Homebrew/actions/': The requested URL returned error: 403
  Error: The process '/usr/bin/git' failed with exit code 128
```

Specifically, this is for the `Homebrew/actions`, `Homebrew/homebrew-bundle`, and `Homebrew/ruby-macho` repos.

Looks like a permissions issue. Does @BrewTestBot have write access to those repos?

**Comment by MikeMcQuaid** [comment]
> Specifically, this is for the `Homebrew/actions`, `Homebrew/homebrew-bundle`, and `Homebrew/ruby-macho` repos.
> 
> Does @BrewTestBot have write access to those repos?

It did not but does now 👍🏻

**Comment by Rylan12** [comment]
Thanks, @MikeMcQuaid! Can you also rerun [this workflow](https://github.com/Homebrew/.github/actions/runs/420975216) now that the access issues' been fixed?

**Comment by MikeMcQuaid** [comment]
@Rylan12 done

**Comment by Rylan12** [comment]
@MikeMcQuaid not seeing it in the [actions tab](https://github.com/Homebrew/.github/actions?query=workflow%3A%22Sync+triage+configurations%22). Am I missing it?

**Comment by MikeMcQuaid** [comment]
@Rylan12 Looks all 🟢 now 🎉

**Pull request merged**
