### PR TITLE
Sync homebrew-autoupdate

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Will defer to @domt4 whether or not this is a good idea/desirable but figured I'd open a PR for discussion.

### CODE REVIEW

**Review by Rylan12 — APPROVED** [review]
👍 from me assuming @DomT4 is on board.

Since `Homebrew/homebrew-autoupdate` doesn't yet have a `.github.workflows` directory, I think the auto-sync workflow will probably fail. Either the workflow should be updated to create those directories or we can just add a quick commit to `Homebrew/homebrew-autoupdate` to add them.

**Comment by MikeMcQuaid** [comment]
Good catch, thanks @Rylan12.

**Review by SMillerDev — COMMENTED** [review]
WFM

**Review by DomT4 — APPROVED** [review]
Assuming I'm understanding this repo correctly this essentially makes sure `autoupdate` has Homebrew's `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md`? That's cool with me, I've been intending to add those sorts of documents.

**Comment by Rylan12** [comment]
This PR will add a `triage-issues` workflow to the `autoupdate` repo that is always synced with the ["main copy"](https://github.com/Homebrew/.github/blob/master/.github/workflows/triage-issues.yml) in this repo.

This workflow, if added to the `autoupdate` repo, will mark issues as stale after they've had no activity for 21 days, and close issues that are marked as stale after 7 more days of inactivity. It will also lock threads that have been inactive for 30 days. We use this in all of the main Homebrew organization repositories to manage issues, so syncing with this is just a good way to make sure we're being consistent.

If we update the global configuration here, you'll get an automated PR from @BrewTestBot making the corresponding change to the `autoupdate` repo. For example: https://github.com/Homebrew/homebrew-bundle/pull/945

---

The other stuff you mentioned isn't affected by this PR. Since Homebrew/homebrew-autoupdate is now within the Homebrew organization, I believe that the `CODE_OF_CONDUCT.md`, `FUNDING.yml`, and `config.yml` files will already "apply" to that repo as well. For example, if you open a new issue (currently), you'll see this:

Screen Shot 2021-04-15 at 1 11 49 AM

and this:

Screen Shot 2021-04-15 at 1 12 03 AM

Both of those link back to the [`CODE_OF_CONDUCT.md`](https://github.com/Homebrew/.github/blob/2262cdd015a1748def52ede65897bbb16b3643f3/CODE_OF_CONDUCT.md) file in this repo.

A `CONTRIBUTING.md` file, though, won't be automatically created.

**Comment by DomT4** [comment]
Thanks @Rylan12. As noted elsewhere a lot of this automation was not around the last time I was, heh, so for now I'm a bit of a fossil. I have a few tracking issues lingering in the repo but I assume there's either a way to stop BTB closing/locking those or if it does I'll just be able to reopen/unlock it as desired/necessary? In which case this PR is still 👍🏻 with me.

> For example, if you open a new issue (currently), you'll see this:

That's handy. Glad those documents have been automatically applied.

**Comment by SMillerDev** [comment]
> but I assume there's either a way to stop BTB closing/locking those or if it does I'll just be able to reopen/unlock it as desired/necessary?

Any of these labels will do that:
https://github.com/Homebrew/.github/blob/master/.github/workflows/triage-issues.yml#L36-L37

**Comment by DomT4** [comment]
Have applied a few of those to intended persistent issues, thanks @SMillerDev.

**Comment by MikeMcQuaid** [comment]
Sounds all good here, thanks all ❤️

**Pull request merged**
